name: hierarchy_hybrid_local_v2
target: model_hierarchy_hybrid.HierarchicalMambaHybrid
params:
    img_dim: 32
    in_channels: 4
    out_channels: 4
    patch_size: 1
    embed_dim: 192
    scan_type: v2
    use_pe: 2
    hierarchy_window_size: 2
    hierarchy_stride: 2
    first_layer_stride: 2
    hierarchy_stage_depth: 2
    hierarchy_max_stages: null
    hierarchy_allow_partial: false
    context_compress_type: mean
    share_stage_processor: false
    hierarchical_output_mode: prediction
    use_multiscale_fusion_head: true
    fusion_mode: concat
    fusion_selected_stages: "32,16,8"
    fusion_anchor_resolution: 4
    decoder_anchor_resolution: 8
    fusion_stage_dim: 320
    fusion_stage_dim_overrides: "8:256,16:320,32:384"
    fusion_gate_type: stage_timestep
    fusion_pos_embed_type: anchor_shared
    fusion_block_depth: 3
    fusion_stage_depth_overrides: "16:2,32:4"
    fusion_channel_gate_stages: "8"
    fusion_use_spatial_gate: true
    fusion_conv_depth: 1
    fusion_pre_mamba_conv_depth: 1
    fusion_post_mamba_conv_depth: 1
    anchor_builder_depth: 3
    fusion_prediction_head_type: anchor_conv_upsample
    fusion_logging_verbose: true
    highres_stage_depth: 3
    bottleneck_stage_depth: 2
    downsample_use_premix: true
    downsample_premix_depth: 0
    downsample_conv_type: standard
    highres_local_conv_depth: 2
    highres_local_conv_type: standard
    prediction_head_conv_depth: 2
    prediction_head_conv_type: standard
    final_skip_refiner_depth: 0
    final_skip_refiner_conv_type: standard
    final_skip_refiner_use_channel_gate: true
    final_skip_refiner_use_spatial_gate: true
