#!/usr/bin/env bash
set -euo pipefail

# Factorized top-4 router preset for 1024px images / 128x128 latents.
# Uses routed stages 128/64/32/16 with an always-on 8x8 bottleneck anchor.

export MODEL_CONFIG="${MODEL_CONFIG:-hierarchy_hybrid_local_v2}"
export IMAGE_SIZE="${IMAGE_SIZE:-1024}"
export MODEL_IMG_DIM="${MODEL_IMG_DIM:-128}"
export FUSION_ANCHOR_RESOLUTION="${FUSION_ANCHOR_RESOLUTION:-8}"
export DECODER_ANCHOR_RESOLUTION="${DECODER_ANCHOR_RESOLUTION:-8}"
if [[ -z "${FUSION_SELECTED_STAGES:-}" ]]; then
  FUSION_SELECTED_STAGES="${MODEL_IMG_DIM}"
  current="${MODEL_IMG_DIM}"
  while [[ "${current}" -gt "${FUSION_ANCHOR_RESOLUTION}" ]]; do
    current=$((current / 2))
    if [[ "${current}" -gt "${FUSION_ANCHOR_RESOLUTION}" ]]; then
      FUSION_SELECTED_STAGES+=",${current}"
    fi
  done
  export FUSION_SELECTED_STAGES
fi

export USE_FACTORIZED_TOP4_ROUTER="${USE_FACTORIZED_TOP4_ROUTER:-true}"
export ROUTED_STAGE_RESOLUTIONS="${ROUTED_STAGE_RESOLUTIONS:-auto}"
export ROUTED_STAGE_COUNT="${ROUTED_STAGE_COUNT:-4}"
export INCLUDE_ANCHOR_IN_STAGE_ROUTER="${INCLUDE_ANCHOR_IN_STAGE_ROUTER:-true}"
export STAGE_ROUTER_TOP_K="${STAGE_ROUTER_TOP_K:-4}"
export STAGE_ROUTER_WEIGHT_FLOOR="${STAGE_ROUTER_WEIGHT_FLOOR:-0.0}"
export STAGE_ROUTER_WEIGHT_MODE="${STAGE_ROUTER_WEIGHT_MODE:-selection}"

export USE_MAMBA_SIZE_ROUTER="${USE_MAMBA_SIZE_ROUTER:-true}"
export MAMBA_SIZE_ROUTER_STAGES="${MAMBA_SIZE_ROUTER_STAGES:-auto}"
export MAMBA_SIZE_PRESETS="${MAMBA_SIZE_PRESETS:-small:1:0.75,base:2:1.0,large:4:1.25}"
export MAMBA_SIZE_ROUTER_WEIGHT_MODE="${MAMBA_SIZE_ROUTER_WEIGHT_MODE:-selection}"

export USE_COMPRESSION_ROUTER="${USE_COMPRESSION_ROUTER:-true}"
export COMPRESSION_ROUTER_STAGES="${COMPRESSION_ROUTER_STAGES:-auto}"

export LOCAL_MAMBA_STAGE_RESOLUTIONS="${LOCAL_MAMBA_STAGE_RESOLUTIONS:-128,64}"
export LOCAL_MAMBA_WINDOW_SIZE_OVERRIDES="${LOCAL_MAMBA_WINDOW_SIZE_OVERRIDES:-128:8,64:8}"
export LOCAL_MAMBA_SHIFT_RESOLUTIONS="${LOCAL_MAMBA_SHIFT_RESOLUTIONS:-64}"

export USE_CHECKPOINT="${USE_CHECKPOINT:-true}"
export BATCH_SIZE_PER_GPU="${BATCH_SIZE_PER_GPU:-8}"
export VAL_BATCH_SIZE_PER_GPU="${VAL_BATCH_SIZE_PER_GPU:-${BATCH_SIZE_PER_GPU}}"
export GRAD_ACCUM_STEPS="${GRAD_ACCUM_STEPS:-4}"
export SAMPLE_FID_BS="${SAMPLE_FID_BS:-2}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
exec bash "${SCRIPT_DIR}/train_facehq1024_hierarchy_hybrid_local_v2_2gpu.sh" "$@"
