#!/usr/bin/env bash
set -euo pipefail

# Factorized-router preset for 256px images / 32x32 latents.
# Default routed stages are 32/16/8, with all three selected each step.

export DATA_CONFIG="${DATA_CONFIG:-facehq_1024}"
export DATA_TAR_BASE="${DATA_TAR_BASE:-/SSD4/yjjung/datasets/celeba_hq_256_hf_shard/}"
export IMAGE_SIZE="${IMAGE_SIZE:-256}"
export MODEL_IMG_DIM="${MODEL_IMG_DIM:-32}"
export FUSION_ANCHOR_RESOLUTION="${FUSION_ANCHOR_RESOLUTION:-8}"
export DECODER_ANCHOR_RESOLUTION="${DECODER_ANCHOR_RESOLUTION:-${FUSION_ANCHOR_RESOLUTION}}"

export ROUTED_STAGE_COUNT="${ROUTED_STAGE_COUNT:-3}"
export STAGE_ROUTER_TOP_K="${STAGE_ROUTER_TOP_K:-3}"
export INCLUDE_ANCHOR_IN_STAGE_ROUTER="${INCLUDE_ANCHOR_IN_STAGE_ROUTER:-true}"

export USE_FACTORIZED_TOP4_ROUTER="${USE_FACTORIZED_TOP4_ROUTER:-true}"
export USE_COMPRESSION_ROUTER="${USE_COMPRESSION_ROUTER:-true}"
export USE_MAMBA_SIZE_ROUTER="${USE_MAMBA_SIZE_ROUTER:-false}"

export ROUTED_STAGE_RESOLUTIONS="${ROUTED_STAGE_RESOLUTIONS:-auto}"
export COMPRESSION_ROUTER_STAGES="${COMPRESSION_ROUTER_STAGES:-auto}"
export MAMBA_SIZE_ROUTER_STAGES="${MAMBA_SIZE_ROUTER_STAGES:-auto}"
export STAGE_ROUTER_WEIGHT_FLOOR="${STAGE_ROUTER_WEIGHT_FLOOR:-0.0}"
export STAGE_ROUTER_WEIGHT_MODE="${STAGE_ROUTER_WEIGHT_MODE:-selection}"
export MAMBA_SIZE_ROUTER_WEIGHT_MODE="${MAMBA_SIZE_ROUTER_WEIGHT_MODE:-selection}"

export FUSION_MODE="${FUSION_MODE:-gated_sum}"
export FUSION_STAGE_DIM="${FUSION_STAGE_DIM:-256}"
export FUSION_STAGE_DIM_OVERRIDES="${FUSION_STAGE_DIM_OVERRIDES:-16:320,32:384}"
export FUSION_BLOCK_DEPTH="${FUSION_BLOCK_DEPTH:-3}"
export FUSION_STAGE_DEPTH_OVERRIDES="${FUSION_STAGE_DEPTH_OVERRIDES:-16:2,32:4}"
export FUSION_CHANNEL_GATE_STAGES="${FUSION_CHANNEL_GATE_STAGES:-16,32}"
export FUSION_USE_SPATIAL_GATE="${FUSION_USE_SPATIAL_GATE:-false}"

export FINAL_SKIP_REFINER_DEPTH="${FINAL_SKIP_REFINER_DEPTH:-2}"
export FINAL_SKIP_REFINER_USE_CHANNEL_GATE="${FINAL_SKIP_REFINER_USE_CHANNEL_GATE:-true}"
export FINAL_SKIP_REFINER_USE_SPATIAL_GATE="${FINAL_SKIP_REFINER_USE_SPATIAL_GATE:-false}"

export USE_CHECKPOINT="${USE_CHECKPOINT:-true}"
export BATCH_SIZE_PER_GPU="${BATCH_SIZE_PER_GPU:-64}"
export VAL_BATCH_SIZE_PER_GPU="${VAL_BATCH_SIZE_PER_GPU:-${BATCH_SIZE_PER_GPU}}"
export NUM_WORKERS="${NUM_WORKERS:-4}"
export VAL_NUM_WORKERS="${VAL_NUM_WORKERS:-1}"
export GRAD_ACCUM_STEPS="${GRAD_ACCUM_STEPS:-1}"
export SAMPLE_FID_BS="${SAMPLE_FID_BS:-8}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
exec bash "${SCRIPT_DIR}/train_hierarchy_hybrid_factorized_router_2gpu.sh" "$@"
