#!/usr/bin/env bash
set -euo pipefail

# Aux-4x4 fine-tuning preset for the FID 13.46 native-skip configuration.
# This script intentionally resumes from the known checkpoint. Use
# train_facehq1024_hierarchy_hybrid_local_v2_aux4x4_scratch_2gpu.sh for
# from-scratch aux training.

export MASTER_PORT="${MASTER_PORT:-8875}"
export CUDA_DEVICES="${CUDA_DEVICES:-0,1}"
export NUM_PROCESSES="${NUM_PROCESSES:-2}"
export BATCH_SIZE_PER_GPU="${BATCH_SIZE_PER_GPU:-32}"
export VAL_BATCH_SIZE_PER_GPU="${VAL_BATCH_SIZE_PER_GPU:-${BATCH_SIZE_PER_GPU}}"
export SAMPLE_FID_BS="${SAMPLE_FID_BS:-4}"
export TRAIN_STEPS="${TRAIN_STEPS:-390000}"
export OPTIM_LR="${OPTIM_LR:-2e-5}"
export CKPT="${CKPT:-/SSD4/vipnu/hierarchical_zigma_v1/zigma/outputs/hierarchy_hybrid_local_v2_facehq_1024_bs32/2026-04-15_23-17-06_None/checkpoints/0300000.pt}"

export DATA_CONFIG="${DATA_CONFIG:-facehq_1024}"
export DATA_TAR_BASE="${DATA_TAR_BASE:-/SSD4/vipnu/datasets/celeba_hq_256_hf_shard/}"
export IMAGE_SIZE="${IMAGE_SIZE:-256}"
if [[ -z "${TRAIN_SHARDS:-}" ]]; then
  export TRAIN_SHARDS='train-{000000..000029}.tar'
else
  export TRAIN_SHARDS
fi
if [[ -z "${VAL_SHARDS:-}" ]]; then
  export VAL_SHARDS="${TRAIN_SHARDS}"
else
  export VAL_SHARDS
fi

export MODEL_CONFIG="${MODEL_CONFIG:-hierarchy_hybrid_local_v2}"
export MODEL_IMG_DIM="${MODEL_IMG_DIM:-32}"
export EMBED_DIM="${EMBED_DIM:-192}"
export SCAN_TYPE="${SCAN_TYPE:-v2}"
export WINDOW_SIZE="${WINDOW_SIZE:-2}"
export FIRST_LAYER_STRIDE="${FIRST_LAYER_STRIDE:-2}"
export WINDOW_STRIDE="${WINDOW_STRIDE:-2}"
export STAGE_DEPTH="${STAGE_DEPTH:-2}"
export HIGHRES_STAGE_DEPTH="${HIGHRES_STAGE_DEPTH:-3}"
export BOTTLENECK_STAGE_DEPTH="${BOTTLENECK_STAGE_DEPTH:-2}"
export CONTEXT_COMPRESS_TYPE="${CONTEXT_COMPRESS_TYPE:-mean}"
export SHARE_STAGE_PROCESSOR="${SHARE_STAGE_PROCESSOR:-false}"
export USE_CHECKPOINT="${USE_CHECKPOINT:-false}"

export DOWNSAMPLE_USE_PREMIX="${DOWNSAMPLE_USE_PREMIX:-true}"
export DOWNSAMPLE_PREMIX_DEPTH="${DOWNSAMPLE_PREMIX_DEPTH:-0}"
export DOWNSAMPLE_CONV_TYPE="${DOWNSAMPLE_CONV_TYPE:-standard}"
export HIGHRES_LOCAL_CONV_DEPTH="${HIGHRES_LOCAL_CONV_DEPTH:-2}"
export HIGHRES_LOCAL_CONV_TYPE="${HIGHRES_LOCAL_CONV_TYPE:-standard}"
export PREDICTION_HEAD_CONV_DEPTH="${PREDICTION_HEAD_CONV_DEPTH:-2}"
export PREDICTION_HEAD_CONV_TYPE="${PREDICTION_HEAD_CONV_TYPE:-standard}"
export FINAL_SKIP_REFINER_DEPTH="${FINAL_SKIP_REFINER_DEPTH:-2}"
export FINAL_SKIP_REFINER_CONV_TYPE="${FINAL_SKIP_REFINER_CONV_TYPE:-standard}"
export FINAL_SKIP_REFINER_USE_CHANNEL_GATE="${FINAL_SKIP_REFINER_USE_CHANNEL_GATE:-true}"
export FINAL_SKIP_REFINER_USE_SPATIAL_GATE="${FINAL_SKIP_REFINER_USE_SPATIAL_GATE:-false}"

export USE_MULTISCALE_FUSION_HEAD="${USE_MULTISCALE_FUSION_HEAD:-true}"
export FUSION_MODE="${FUSION_MODE:-gated_sum}"
export FUSION_SELECTED_STAGES="${FUSION_SELECTED_STAGES:-32,16}"
export FUSION_ANCHOR_RESOLUTION="${FUSION_ANCHOR_RESOLUTION:-8}"
export DECODER_ANCHOR_RESOLUTION="${DECODER_ANCHOR_RESOLUTION:-8}"
export FUSION_STAGE_DIM="${FUSION_STAGE_DIM:-256}"
export FUSION_STAGE_DIM_OVERRIDES="${FUSION_STAGE_DIM_OVERRIDES:-16:320,32:384}"
export FUSION_GATE_TYPE="${FUSION_GATE_TYPE:-stage_timestep}"
export FUSION_POS_EMBED_TYPE="${FUSION_POS_EMBED_TYPE:-anchor_shared}"
export FUSION_BLOCK_DEPTH="${FUSION_BLOCK_DEPTH:-3}"
export FUSION_STAGE_DEPTH_OVERRIDES="${FUSION_STAGE_DEPTH_OVERRIDES:-16:2,32:4}"
export FUSION_CHANNEL_GATE_STAGES="${FUSION_CHANNEL_GATE_STAGES:-16,32}"
export FUSION_USE_SPATIAL_GATE="${FUSION_USE_SPATIAL_GATE:-false}"
export FUSION_CONV_DEPTH="${FUSION_CONV_DEPTH:-1}"
export FUSION_PRE_MAMBA_CONV_DEPTH="${FUSION_PRE_MAMBA_CONV_DEPTH:-1}"
export FUSION_POST_MAMBA_CONV_DEPTH="${FUSION_POST_MAMBA_CONV_DEPTH:-1}"
export ANCHOR_BUILDER_DEPTH="${ANCHOR_BUILDER_DEPTH:-3}"
export FUSION_PREDICTION_HEAD_TYPE="${FUSION_PREDICTION_HEAD_TYPE:-anchor_conv_upsample}"
export FUSION_LOGGING_VERBOSE="${FUSION_LOGGING_VERBOSE:-true}"

export USE_AUX_4X4_CONTEXT="${USE_AUX_4X4_CONTEXT:-true}"
export AUX_4X4_INJECT_TARGET="${AUX_4X4_INJECT_TARGET:-final_map}"
export AUX_4X4_CONTEXT_RESOLUTION="${AUX_4X4_CONTEXT_RESOLUTION:-4}"
export AUX_4X4_TARGET_RESOLUTION="${AUX_4X4_TARGET_RESOLUTION:-auto}"
export AUX_4X4_PREPOOL_DEPTH="${AUX_4X4_PREPOOL_DEPTH:-1}"
export AUX_4X4_CONTEXT_DEPTH="${AUX_4X4_CONTEXT_DEPTH:-1}"
export AUX_4X4_FUSION_DEPTH="${AUX_4X4_FUSION_DEPTH:-2}"
export AUX_4X4_CONV_TYPE="${AUX_4X4_CONV_TYPE:-standard}"
export AUX_4X4_UPSAMPLE_MODE="${AUX_4X4_UPSAMPLE_MODE:-bilinear}"
export AUX_4X4_USE_TIMESTEP_GATE="${AUX_4X4_USE_TIMESTEP_GATE:-true}"
export AUX_4X4_RESIDUAL_SCALE_MULTIPLIER="${AUX_4X4_RESIDUAL_SCALE_MULTIPLIER:-0.5}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
exec bash "${SCRIPT_DIR}/train_facehq1024_hierarchy_hybrid_local_v2_2gpu.sh" "$@"
