#!/usr/bin/env bash
set -euo pipefail

# FID-11.935 big native-skip preset with only the compression-type router enabled.
# The model/router/mamba-size routers stay off. Compression routing is applied to
# both hierarchy compression transitions: 32->16 and 16->8.

export MODEL_CONFIG="${MODEL_CONFIG:-hierarchy_hybrid_local_v2}"
export SCAN_TYPE="${SCAN_TYPE:-v2}"
export CUDA_DEVICES="${CUDA_DEVICES:-0,1,2,3}"
export NUM_PROCESSES="${NUM_PROCESSES:-4}"
export MASTER_PORT="${MASTER_PORT:-8872}"

export DATA_TAR_BASE="${DATA_TAR_BASE:-/SSD4/yjjung/datasets/celeba_hq_256_hf_shard}"
export IMAGE_SIZE="${IMAGE_SIZE:-256}"
export MODEL_IMG_DIM="${MODEL_IMG_DIM:-32}"

export BATCH_SIZE_PER_GPU="${BATCH_SIZE_PER_GPU:-16}"
export VAL_BATCH_SIZE_PER_GPU="${VAL_BATCH_SIZE_PER_GPU:-16}"
export GRAD_ACCUM_STEPS="${GRAD_ACCUM_STEPS:-1}"
export NUM_WORKERS="${NUM_WORKERS:-7}"
export VAL_NUM_WORKERS="${VAL_NUM_WORKERS:-4}"
export SAMPLE_FID_BS="${SAMPLE_FID_BS:-4}"
export USE_CHECKPOINT="${USE_CHECKPOINT:-true}"

export EMBED_DIM="${EMBED_DIM:-256}"
export HIERARCHY_STAGE_DEPTH="${HIERARCHY_STAGE_DEPTH:-3}"
export HIGHRES_STAGE_DEPTH="${HIGHRES_STAGE_DEPTH:-4}"
export BOTTLENECK_STAGE_DEPTH="${BOTTLENECK_STAGE_DEPTH:-4}"

export DOWNSAMPLE_USE_PREMIX="${DOWNSAMPLE_USE_PREMIX:-true}"
export DOWNSAMPLE_PREMIX_DEPTH="${DOWNSAMPLE_PREMIX_DEPTH:-1}"
export DOWNSAMPLE_CONV_TYPE="${DOWNSAMPLE_CONV_TYPE:-standard}"
export HIGHRES_LOCAL_CONV_DEPTH="${HIGHRES_LOCAL_CONV_DEPTH:-3}"
export HIGHRES_LOCAL_CONV_TYPE="${HIGHRES_LOCAL_CONV_TYPE:-standard}"

export FUSION_ANCHOR_RESOLUTION="${FUSION_ANCHOR_RESOLUTION:-8}"
export DECODER_ANCHOR_RESOLUTION="${DECODER_ANCHOR_RESOLUTION:-8}"
export FUSION_SELECTED_STAGES="${FUSION_SELECTED_STAGES:-32,16}"
export FUSION_MODE="${FUSION_MODE:-gated_sum}"
export FUSION_STAGE_DIM="${FUSION_STAGE_DIM:-320}"
export FUSION_STAGE_DIM_OVERRIDES="${FUSION_STAGE_DIM_OVERRIDES:-16:448,32:512}"
export FUSION_BLOCK_DEPTH="${FUSION_BLOCK_DEPTH:-4}"
export FUSION_STAGE_DEPTH_OVERRIDES="${FUSION_STAGE_DEPTH_OVERRIDES:-16:4,32:6}"
export FUSION_CHANNEL_GATE_STAGES="${FUSION_CHANNEL_GATE_STAGES:-16,32}"
export FUSION_USE_SPATIAL_GATE="${FUSION_USE_SPATIAL_GATE:-false}"
export FUSION_CONV_DEPTH="${FUSION_CONV_DEPTH:-1}"
export FUSION_PRE_MAMBA_CONV_DEPTH="${FUSION_PRE_MAMBA_CONV_DEPTH:-1}"
export FUSION_POST_MAMBA_CONV_DEPTH="${FUSION_POST_MAMBA_CONV_DEPTH:-1}"

export PREDICTION_HEAD_CONV_DEPTH="${PREDICTION_HEAD_CONV_DEPTH:-3}"
export PREDICTION_HEAD_CONV_TYPE="${PREDICTION_HEAD_CONV_TYPE:-standard}"
export FINAL_SKIP_REFINER_DEPTH="${FINAL_SKIP_REFINER_DEPTH:-3}"
export FINAL_SKIP_REFINER_CONV_TYPE="${FINAL_SKIP_REFINER_CONV_TYPE:-standard}"
export FINAL_SKIP_REFINER_USE_CHANNEL_GATE="${FINAL_SKIP_REFINER_USE_CHANNEL_GATE:-true}"
export FINAL_SKIP_REFINER_USE_SPATIAL_GATE="${FINAL_SKIP_REFINER_USE_SPATIAL_GATE:-false}"

export USE_FACTORIZED_TOP4_ROUTER="${USE_FACTORIZED_TOP4_ROUTER:-false}"
export USE_MAMBA_SIZE_ROUTER="${USE_MAMBA_SIZE_ROUTER:-false}"

export USE_COMPRESSION_ROUTER="${USE_COMPRESSION_ROUTER:-true}"
export COMPRESSION_ROUTER_STAGES="${COMPRESSION_ROUTER_STAGES:-16,8}"

export NOTE="${NOTE:-facehq1024_fid11935_only_compress_type_router}"
export TIMESTAMP="${TIMESTAMP:-only_compress_type_router}"
export WANDB_NAME="${WANDB_NAME:-${NOTE}}"
export WANDB_TAGS="${WANDB_TAGS:-fid11935,only_compress_type_router,sparse_top1,compress_stage16_8,native_skip,gated_sum,no_stage_router,no_mamba_size_router}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
exec bash "${SCRIPT_DIR}/train_facehq1024_hierarchy_hybrid_local_v2_2gpu.sh" "$@"
