#!/usr/bin/env bash
set -euo pipefail

# Novelty-preserving, attention-free preset:
# - reduces bottleneck over-compression with an 8x8 anchor
# - adds local-window Mamba only at 32x32 to protect high-frequency details
# - keeps lower-resolution stages global for better train_steps_per_sec
# - uses stronger zigzag scans only where spatial continuity matters most

export MODEL_CONFIG="${MODEL_CONFIG:-hierarchy_hybrid_local_v2}"
export SCAN_TYPE="${SCAN_TYPE:-v2}"

export FUSION_ANCHOR_RESOLUTION="${FUSION_ANCHOR_RESOLUTION:-8}"
export DECODER_ANCHOR_RESOLUTION="${DECODER_ANCHOR_RESOLUTION:-8}"

export DOWNSAMPLE_USE_PREMIX="${DOWNSAMPLE_USE_PREMIX:-true}"
export DOWNSAMPLE_PREMIX_DEPTH="${DOWNSAMPLE_PREMIX_DEPTH:-1}"
export DOWNSAMPLE_CONV_TYPE="${DOWNSAMPLE_CONV_TYPE:-standard}"

export HIGHRES_LOCAL_CONV_DEPTH="${HIGHRES_LOCAL_CONV_DEPTH:-2}"
export HIGHRES_LOCAL_CONV_TYPE="${HIGHRES_LOCAL_CONV_TYPE:-standard}"

export FUSION_STAGE_DEPTH_OVERRIDES="${FUSION_STAGE_DEPTH_OVERRIDES:-16:2,32:4}"
export FUSION_CHANNEL_GATE_STAGES="${FUSION_CHANNEL_GATE_STAGES:-16,32}"
export FUSION_PRE_MAMBA_CONV_DEPTH="${FUSION_PRE_MAMBA_CONV_DEPTH:-1}"
export FUSION_POST_MAMBA_CONV_DEPTH="${FUSION_POST_MAMBA_CONV_DEPTH:-1}"
export ANCHOR_BUILDER_DEPTH="${ANCHOR_BUILDER_DEPTH:-2}"

export STAGE_SCAN_TYPE_OVERRIDES="${STAGE_SCAN_TYPE_OVERRIDES:-16:zigzagN4,32:zigzagN8}"
export LOCAL_MAMBA_STAGE_RESOLUTIONS="${LOCAL_MAMBA_STAGE_RESOLUTIONS:-32}"
export LOCAL_MAMBA_WINDOW_SIZE_OVERRIDES="${LOCAL_MAMBA_WINDOW_SIZE_OVERRIDES:-32:8}"
export LOCAL_MAMBA_SHIFT_RESOLUTIONS="${LOCAL_MAMBA_SHIFT_RESOLUTIONS:-32}"

export PREDICTION_HEAD_CONV_DEPTH="${PREDICTION_HEAD_CONV_DEPTH:-2}"
export PREDICTION_HEAD_CONV_TYPE="${PREDICTION_HEAD_CONV_TYPE:-standard}"

export FINAL_SKIP_REFINER_DEPTH="${FINAL_SKIP_REFINER_DEPTH:-2}"
export FINAL_SKIP_REFINER_CONV_TYPE="${FINAL_SKIP_REFINER_CONV_TYPE:-standard}"
export FINAL_SKIP_REFINER_USE_CHANNEL_GATE="${FINAL_SKIP_REFINER_USE_CHANNEL_GATE:-true}"
export FINAL_SKIP_REFINER_USE_SPATIAL_GATE="${FINAL_SKIP_REFINER_USE_SPATIAL_GATE:-true}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
exec bash "${SCRIPT_DIR}/train_facehq1024_hierarchy_hybrid_local_v2_2gpu.sh" "$@"
